# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation_System', '0007_auto_20170104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movies_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recommendation_System.Movie'),
        ),
    ]
