# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation_System', '0008_auto_20170107_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movies_id',
            new_name='movies',
        ),
    ]
